/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2020-06-04 15:05:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lirongjie_005fshenyuqi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class draw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

{
	String str;
	out.println("var user_name=\""			+(((str=request.getParameter("user_name"			))==null)?"NoName":str)+"\";");
	out.println("var pass_word=\""			+(((str=request.getParameter("pass_word"			))==null)?"NoPassword":str)+"\";");	
	out.println("var scene_name=\""			+(((str=request.getParameter("scene_name"			))==null)?"":str)+"\";");
	out.println("var link_name=\""			+(((str=request.getParameter("link_name"			))==null)?"":str)+"\";");
	out.println("var change_part=\""		+(((str=request.getParameter("change_part"			))==null)?"":str)+"\";");
	out.println("var change_component=\""	+(((str=request.getParameter("change_component"		))==null)?"":str)+"\";");
	out.println("var canvas_height=\""		+(((str=request.getParameter("canvas_height"		))==null)?"0.8":str)+"\";");
	out.println("var rotate_angle=\""		+(((str=request.getParameter("rotate_angle"			))==null)?"0.0":str)+"\";");
}


      out.write("\r\n");
      out.write("var render_object;\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../interface.jsp?function_name=construct_render_object\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../chinese/draw.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./lirongjie_shenyuqi.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function hide_all()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"mouse_table\").\t\thidden=\"hidden\";\r\n");
      out.write("\tdocument.getElementById(\"content_table\").\thidden=\"hidden\";\r\n");
      out.write("\tdocument.getElementById(\"camera_table\").\thidden=\"hidden\";\r\n");
      out.write("\tdocument.getElementById(\"operation_table\").\thidden=\"hidden\";\r\n");
      out.write("\tdocument.getElementById(\"parameter_table\").\thidden=\"hidden\";\r\n");
      out.write("\tdocument.getElementById(\"mount_table\").\t\thidden=\"hidden\";\r\n");
      out.write("}\r\n");
      out.write("function switch_function(name)\r\n");
      out.write("{\r\n");
      out.write("\thide_all();\r\n");
      out.write("\t\r\n");
      out.write("\tvar opts=document.getElementById(name),select_value=opts.value;\r\n");
      out.write("\tfor(var i=0;i<opts.options.length;i++)\r\n");
      out.write("\t\topts.options[i].selected=\"\";\r\n");
      out.write("\t\r\n");
      out.write("\tswitch(select_value){\r\n");
      out.write("\tcase \"鼠标功能\":\tdocument.getElementById(\"mouse_table\").\t\thidden=\"\";\tbreak;\r\n");
      out.write("\tcase \"内容显示\":\tdocument.getElementById(\"content_table\").\thidden=\"\";\tbreak;\r\n");
      out.write("\tcase \"相机操作\":\tdocument.getElementById(\"camera_table\").\thidden=\"\";\tbreak;\r\n");
      out.write("\tcase \"组件操作\":\tdocument.getElementById(\"operation_table\").\thidden=\"\";\tbreak;\r\n");
      out.write("\tcase \"系统参数\":\tdocument.getElementById(\"parameter_table\").\thidden=\"\";\tbreak;\r\n");
      out.write("\tcase \"拼装控制\":\tdocument.getElementById(\"mount_table\").\t\thidden=\"\";\tbreak;\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function body_onload()\r\n");
      out.write("{\r\n");
      out.write("\thide_all();\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.oncontextmenu = function(){return false;}\r\n");
      out.write("\t\r\n");
      out.write("\tconstruct_render_object(document.getElementById(\"my_canvas\"),\r\n");
      out.write("\t\tuser_name,pass_word,\"chinese\",scene_name,link_name,\r\n");
      out.write("\t\t[\r\n");
      out.write("\t\t\t[\"change_part\",\t\t\tchange_part],\r\n");
      out.write("\t\t\t[\"change_component\",\tchange_component],\r\n");
      out.write("\t\t\t[\"transfer_type\",\t\ttrue],\r\n");
      out.write("\t\t\t[\"max_loading_number\",\t5]\r\n");
      out.write("\t\t],\r\n");
      out.write("\t\tfunction(my_render_object)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\trender_object=my_render_object;\r\n");
      out.write("\t\t\tdocument.title=render_object.title;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\trender_object.canvas.width =window.innerWidth*0.975;\r\n");
      out.write("\t\t\trender_object.canvas.height=window.innerHeight*canvas_height;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\teclipse(false);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\trender_object.utility.call_server_component(\"camera_operation_component\",\"all\",\r\n");
      out.write("\t\t\t\t\t[[\"operation\",\"client_parameter\"],\t[\"state_name\",\"discard_lod\"],\t[\"state_value\",\"off\"]]);\r\n");
      out.write("\t\t\trender_object.utility.call_server_component(\"camera_operation_component\",\"all\",\r\n");
      out.write("\t\t\t\t\t[[\"operation\",\"client_parameter\"],\t[\"state_name\",\"selection_lod\"],\t[\"state_value\",\"off\"]]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("select {color:rgb(0,0,192);background-color:rgb(128,128,0);border-radius:10px};\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"body_onload();\"\tonresize=\"body_onresize(null);\"\tonunload=\"render_object.terminate();\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align:left\">\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t\r\n");
      out.write("\t<canvas id=\"my_canvas\" \t\ttabindex=\"0\"\t></canvas><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<table style=\"position:absolute;left:50px;top:10px;color:rgb(0,0,192)\"><tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<td><table><tr>\r\n");
      out.write("\t<td>功能切换<br/>\r\n");
      out.write("\t<select  id=\"switch_function_id\"\tonclick=\"switch_function('switch_function_id');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>鼠标功能</option>\r\n");
      out.write("\t\t<option>内容显示</option>\r\n");
      out.write("\t\t<option>相机操作</option>\r\n");
      out.write("\t\t<option>组件操作</option>\r\n");
      out.write("\t\t<option>系统参数</option>\r\n");
      out.write("\t\t<option>拼装控制</option>\r\n");
      out.write("\t</select><br/><br/><br/>\r\n");
      out.write("\t</td></tr></table>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td><table><tr id=\"mouse_table\">\r\n");
      out.write("\t<td>鼠标功能:&nbsp;&nbsp;&nbsp;&nbsp;</td><td>旋转视口<br/>\r\n");
      out.write("\t<select  id=\"mouse_for_view_rotate\"\ttitle=\"把鼠标设置为旋转视口\"\tonclick=\"switch_mouse_function_to_rotate_move('mouse_for_view_rotate');\">\r\n");
      out.write("\t\t<optgroup label=\"旋转视口\">\t\r\n");
      out.write("\t\t\t<option>旋转视口</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>自由旋转</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>X轴旋转</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>局部X轴</option>\r\n");
      out.write("\t\t\t<option>局部Y轴</option>\r\n");
      out.write("\t\t\t<option>局部Z轴</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>左右旋转</option>\r\n");
      out.write("\t\t\t<option>上下旋转</option>\r\n");
      out.write("\t\t\t<option>视口旋转</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>平移视口<br/>\r\n");
      out.write("\t<select  id=\"mouse_for_view_move\"\ttitle=\"把鼠标设置为平移视口\"\tonclick=\"switch_mouse_function_to_rotate_move('mouse_for_view_move');\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"平移视口\">\r\n");
      out.write("\t\t\t<option>平移视口</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>X轴平移</option>\r\n");
      out.write("\t\t\t<option>Y轴平移</option>\r\n");
      out.write("\t\t\t<option>Z轴平移</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>局部X轴</option>\r\n");
      out.write("\t\t\t<option>局部Y轴</option>\r\n");
      out.write("\t\t\t<option>局部Z轴</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>左右平移</option>\r\n");
      out.write("\t\t\t<option>上下平移</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>XY面平移</option>\r\n");
      out.write("\t\t\t<option>YZ面平移</option>\r\n");
      out.write("\t\t\t<option>ZX面平移</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>局部XY面</option>\r\n");
      out.write("\t\t\t<option>局部YZ面</option>\r\n");
      out.write("\t\t\t<option>局部ZX面</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>视面平移</option>\t\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>指定视口<br/>\r\n");
      out.write("\t<select  id=\"mouse_for_view_select\"\ttitle=\"把鼠标设置为指定视口\"\tonclick=\"switch_mouse_function_to_select_component_or_view('mouse_for_view_select');\">\r\n");
      out.write("\t\t<optgroup label=\"指定视口\">\t\r\n");
      out.write("\t\t\t<option>指定视口-</option>\r\n");
      out.write("\t\t\t<option>指定视口+</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t</td><td>旋转组件<br/>\r\n");
      out.write("\t<select  id=\"mouse_for_component_rotate\"\ttitle=\"把鼠标设置为旋转组件\"\tonclick=\"switch_mouse_function_to_rotate_move('mouse_for_component_rotate');\">\r\n");
      out.write("\t\t<optgroup label=\"旋转组件\">\t\r\n");
      out.write("\t\t\t<option>旋转组件</option>\r\n");
      out.write("\t\t\t<option>自由旋转</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>X轴旋转</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>局部X轴</option>\r\n");
      out.write("\t\t\t<option>局部Y轴</option>\r\n");
      out.write("\t\t\t<option>局部Z轴</option>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<option>左右旋转</option>\r\n");
      out.write("\t\t\t<option>上下旋转</option>\r\n");
      out.write("\t\t\t<option>视口旋转</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>平移组件<br/>\r\n");
      out.write("\t<select  id=\"mouse_for_component_move\"\t\ttitle=\"把鼠标设置为平移组件\"\tonclick=\"switch_mouse_function_to_rotate_move('mouse_for_component_move');\">\r\n");
      out.write("\t\t<optgroup label=\"平移组件\">\t\r\n");
      out.write("\t\t\t<option>平移组件</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>X轴平移</option>\r\n");
      out.write("\t\t\t<option>Y轴平移</option>\r\n");
      out.write("\t\t\t<option>Z轴平移</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>局部X轴</option>\r\n");
      out.write("\t\t\t<option>局部Y轴</option>\r\n");
      out.write("\t\t\t<option>局部Z轴</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>左右平移</option>\r\n");
      out.write("\t\t\t<option>上下平移</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>XY面平移</option>\r\n");
      out.write("\t\t\t<option>YZ面平移</option>\r\n");
      out.write("\t\t\t<option>ZX面平移</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>局部XY面</option>\r\n");
      out.write("\t\t\t<option>局部YZ面</option>\r\n");
      out.write("\t\t\t<option>局部ZX面</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>视面平移</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>选择组件<br/>\r\n");
      out.write("\t<select  id=\"mouse_for_component_select\"\ttitle=\"把鼠标设置为指定视口\"\tonclick=\"switch_mouse_function_to_select_component_or_view('mouse_for_component_select');\">\r\n");
      out.write("\t\t<optgroup label=\"选择组件\">\t\r\n");
      out.write("\t\t\t<option>选择组件-</option>\r\n");
      out.write("\t\t\t<option>选择组件+</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>标注尺寸<br/>\r\n");
      out.write("\t<select  id=\"tag_select\" title=\"把鼠标设置为标注尺寸\"\t onclick=\"switch_mouse_function_to_tag('tag_select');\">\r\n");
      out.write("\t\t<optgroup label=\"标注尺寸\">\t\r\n");
      out.write("\t\t\t<option>标注尺寸</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>标注X方向</option>\r\n");
      out.write("\t\t\t<option>标注Y方向</option>\r\n");
      out.write("\t\t\t<option>标注Z方向</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>标注局部X方向</option>\r\n");
      out.write("\t\t\t<option>标注局部Y方向</option>\r\n");
      out.write("\t\t\t<option>标注局部Z方向</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>标注左右</option>\r\n");
      out.write("\t\t\t<option>标注上下</option>\r\n");
      out.write("\t\t\t<option>标注里外</option>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>标注XY面</option>\r\n");
      out.write("\t\t\t<option>标注YZ面</option>\r\n");
      out.write("\t\t\t<option>标注ZX面</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>标注局部XY面</option>\r\n");
      out.write("\t\t\t<option>标注局部YZ面</option>\r\n");
      out.write("\t\t\t<option>标注局部ZX面</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<option>标注视面</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr id=\"content_table\"><td>内容显示:&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>显示方式<br/>\r\n");
      out.write("\t<select  id=\"show_method\"\tonclick=\"switch_show_method();\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"显示表面\">\r\n");
      out.write("\t\t\t<option>仅仅显示表面</option>\r\n");
      out.write("\t\t\t<option>显示表面及线框</option>\r\n");
      out.write("\t\t\t<option>显示表面及边线</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"显示隐藏线\">\r\n");
      out.write("\t\t\t<option>显示线框</option>\r\n");
      out.write("\t\t\t<option>显示边线</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"消除隐藏线\">\r\n");
      out.write("\t\t\t<option>显示线框(消隐)</option>\r\n");
      out.write("\t\t\t<option>显示边线(消隐)</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t<optgroup label=\"显示隐藏点\">\r\n");
      out.write("\t\t\t<option>显示点</option>\r\n");
      out.write("\t\t\t<option>隐藏点</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<option>全屏幕显示</option>\r\n");
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>显示内容<br/>\r\n");
      out.write("\t<select  id=\"show_content\"\tonclick=\"switch_show_content();\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<optgroup label=\"显示内容\">\r\n");
      out.write("\t\t\t<option>已拼装组件之一</option>\t\t<option>已拼装组件之二</option>\r\n");
      out.write("\t\t\t<option>未拼装组件之一</option>\t\t<option>未拼装组件之二</option>\r\n");
      out.write("\t\t\t<option>列表组件之一</option>\t\t<option>列表组件之二</option>\r\n");
      out.write("\t\t\t<option>全部组件之一</option>\t\t<option>全部组件之二</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t<optgroup label=\"坐标轴显示\">\r\n");
      out.write("\t\t\t<option>全部显示</option>\r\n");
      out.write("\t\t\t<option>主坐标轴</option>\r\n");
      out.write("\t\t\t<option>选中坐标轴</option>\r\n");
      out.write("\t\t\t<option>全部隐藏</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"方向按钮显示\">\r\n");
      out.write("\t\t\t<option>显示方向按钮</option>\r\n");
      out.write("\t\t\t<option>隐藏方向按钮</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"计算结果显示\">\r\n");
      out.write("\t\t\t<option>材质</option>\r\n");
      out.write("\t\t\t<option>Ux</option>\r\n");
      out.write("\t\t\t<option>Uy</option>\r\n");
      out.write("\t\t\t<option>Uz</option>\r\n");
      out.write("\t\t\t<option>Sxx</option>\r\n");
      out.write("\t\t\t<option>Syy</option>\r\n");
      out.write("\t\t\t<option>Szz</option>\r\n");
      out.write("\t\t\t<option>Sxy</option>\r\n");
      out.write("\t\t\t<option>Sxz</option>\r\n");
      out.write("\t\t\t<option>Syz</option>\r\n");
      out.write("\t\t\t<option>SP3</option>\r\n");
      out.write("\t\t\t<option>SP4</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"等高线数目\">\r\n");
      out.write("\t\t\t<option>5</option>\r\n");
      out.write("\t\t\t<option>10</option>\r\n");
      out.write("\t\t\t<option>20</option>\r\n");
      out.write("\t\t\t<option>40</option>\r\n");
      out.write("\t\t\t<option>50</option>\r\n");
      out.write("\t\t\t<option>80</option>\r\n");
      out.write("\t\t\t<option>100</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"等高线宽度\">\r\n");
      out.write("\t\t\t<option>0.000</option>\r\n");
      out.write("\t\t\t<option>0.020</option>\r\n");
      out.write("\t\t\t<option>0.050</option>\r\n");
      out.write("\t\t\t<option>0.100</option>\r\n");
      out.write("\t\t\t<option>0.125</option>\r\n");
      out.write("\t\t\t<option>0.200</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t</td><td>投影方式<br/>\r\n");
      out.write("\t<select  id=\"project_method\"\tonclick=\"switch_project_method();\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>透视投影</option>\r\n");
      out.write("\t\t<option>正交投影</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>修改方式<br/>\r\n");
      out.write("\t<select  id=\"camera_modify_method\" onchange=\"set_camera_modify_method('camera_modify_method');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"视口修改\">\r\n");
      out.write("\t\t\t<option>修改相机视距</option>\r\n");
      out.write("\t\t\t<option>修改相机视角</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"视口定位\">\r\n");
      out.write("\t\t\t<option>打开视口定位</option>\r\n");
      out.write("\t\t\t<option>关闭视口定位</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"视口定向\">\r\n");
      out.write("\t\t\t<option>打开视口定向</option>\r\n");
      out.write("\t\t\t<option>关闭视口定向</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"视口放大\">\r\n");
      out.write("\t\t\t<option>打开视口放大</option>\r\n");
      out.write("\t\t\t<option>关闭视口放大</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>设置背景<br/>\r\n");
      out.write("\t<select  id=\"camera_background\"\tonclick=\"switch_camera_background();\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>立体背景</option>\r\n");
      out.write("\t\t<option>平面背景</option>\r\n");
      out.write("\t\t<option>颜色背景</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<input type=\"color\" id=\"background_color\" name=\"background_color\" oninput=\"background_color_input();\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</td><td>背景图片<br/>\r\n");
      out.write("\t<select  id=\"camera_background_image\"\tonclick=\"switch_camera_background_image();\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>背景图片一</option>\r\n");
      out.write("\t\t<option>背景图片二</option>\r\n");
      out.write("\t\t<option>背景图片三</option>\r\n");
      out.write("\t\t<option>背景图片四</option>\r\n");
      out.write("\t\t<option>背景图片五</option>\r\n");
      out.write("\t\t<option>背景图片六</option>\r\n");
      out.write("\t\t<option>背景图片七</option>\r\n");
      out.write("\t\t<option>背景图片八</option>\r\n");
      out.write("\t\t<option>背景图片九</option>\r\n");
      out.write("\t\t<option>背景图片十</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr id=\"camera_table\"><td>相机操作:&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td>相机选择<br/>\r\n");
      out.write("\t<select  id=\"camera_id\" onclick=\"switch_camera(-1);\">\r\n");
      out.write("\t\t<option>第一相机</option>\r\n");
      out.write("\t\t<option>第二相机</option>\r\n");
      out.write("\t\t<option>第三相机</option>\r\n");
      out.write("\t\t<option>第四相机</option>\r\n");
      out.write("\t\t<option>第五相机</option>\r\n");
      out.write("\t\t<option>第六相机</option>\r\n");
      out.write("\t\t<option>第七相机</option>\r\n");
      out.write("\t\t<option>第八相机</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>相机定位<br/>\r\n");
      out.write("\t<select  id=\"camera_location\" onchange=\"set_camera_location('camera_location');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"设置相机位置\">\r\n");
      out.write("\t\t\t<option>回退相机视口</option>\r\n");
      out.write("\t\t\t<option>放大缩小视口</option>\r\n");
      out.write("\t\t\t<option>视口大小不变 </option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"相机跟随方向仪\">\r\n");
      out.write("\t\t\t<option>启动跟随方向仪</option>\r\n");
      out.write("\t\t\t<option>校准跟随方向仪</option>\r\n");
      out.write("\t\t\t<option>终止跟随方向仪</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t</td><td>标准方向<br/>\r\n");
      out.write("\t<select  id=\"camera_direction_standard\" onchange=\"set_camera_direction('camera_direction_standard','&type=false');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"视口标准旋转方向\">\r\n");
      out.write("\t\t\t<option>+X+Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X+Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X+Y-Z方向</option>\r\n");
      out.write("\t\t\t<option>+X+Y-Z方向</option>\r\n");
      out.write("\t\t\t<option>+X-Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X-Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X-Y-Z方向</option>\r\n");
      out.write("\t\t\t<option>+X-Y-Z方向</option>\r\n");
      out.write("\t\t\t<option>+X方向</option>\r\n");
      out.write("\t\t\t<option>-X方向</option>\r\n");
      out.write("\t\t\t<option>+Y方向</option>\r\n");
      out.write("\t\t\t<option>-Y方向</option>\r\n");
      out.write("\t\t\t<option>+Z方向</option>\r\n");
      out.write("\t\t\t<option>-Z方向</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>最近方向<br/>\r\n");
      out.write("\t<select  id=\"camera_direction_selection\" onchange=\"set_camera_direction('camera_direction_selection','&type=true');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"视口最近旋转方向\">\r\n");
      out.write("\t\t\t<option>+X+Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X+Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X+Y-Z方向</option>\r\n");
      out.write("\t\t\t<option>+X+Y-Z方向</option>\r\n");
      out.write("\t\t\t<option>+X-Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X-Y+Z方向</option>\r\n");
      out.write("\t\t\t<option>-X-Y-Z方向</option>\r\n");
      out.write("\t\t\t<option>+X-Y-Z方向</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option>+X方向</option>\r\n");
      out.write("\t\t\t<option>-X方向</option>\r\n");
      out.write("\t\t\t<option>+Y方向</option>\r\n");
      out.write("\t\t\t<option>-Y方向</option>\r\n");
      out.write("\t\t\t<option>+Z方向</option>\r\n");
      out.write("\t\t\t<option>-Z方向</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>坐标旋转<br/>\r\n");
      out.write("\t<select  id=\"camera_rotate_1\" onchange=\"rotate_camera('camera_rotate_1');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"X轴旋转\">\r\n");
      out.write("\t\t\t<option>X轴旋转30度</option>\r\n");
      out.write("\t\t\t<option>X轴旋转45度</option>\r\n");
      out.write("\t\t\t<option>X轴旋转60度</option>\r\n");
      out.write("\t\t\t<option>X轴旋转90度</option>\r\n");
      out.write("\t\t\t<option>X轴旋转-30度</option>\r\n");
      out.write("\t\t\t<option>X轴旋转-45度</option>\r\n");
      out.write("\t\t\t<option>X轴旋转-60度</option>\r\n");
      out.write("\t\t\t<option>X轴旋转-90度</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"Y轴旋转\">\r\n");
      out.write("\t\t\t<option>Y轴旋转30度</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转45度</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转60度</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转90度</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转-30度</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转-45度</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转-60度</option>\r\n");
      out.write("\t\t\t<option>Y轴旋转-90度</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"Z轴旋转\">\r\n");
      out.write("\t\t\t<option>Z轴旋转30度</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转45度</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转60度</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转90度</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转-30度</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转-45度</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转-60度</option>\r\n");
      out.write("\t\t\t<option>Z轴旋转-90度</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>视口旋转<br/>\r\n");
      out.write("\t<select  id=\"camera_rotate_2\" onchange=\"rotate_camera('camera_rotate_2');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"视口旋转\">\r\n");
      out.write("\t\t\t<option>视口旋转30度</option>\r\n");
      out.write("\t\t\t<option>视口旋转45度</option>\r\n");
      out.write("\t\t\t<option>视口旋转60度</option>\r\n");
      out.write("\t\t\t<option>视口旋转90度</option>\r\n");
      out.write("\t\t\t<option>视口旋转-30度</option>\r\n");
      out.write("\t\t\t<option>视口旋转-45度</option>\r\n");
      out.write("\t\t\t<option>视口旋转-60度</option>\r\n");
      out.write("\t\t\t<option>视口旋转-90度</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"左右旋转\">\r\n");
      out.write("\t\t\t<option>左右旋转30度</option>\r\n");
      out.write("\t\t\t<option>左右旋转45度</option>\r\n");
      out.write("\t\t\t<option>左右旋转60度</option>\r\n");
      out.write("\t\t\t<option>左右旋转90度</option>\r\n");
      out.write("\t\t\t<option>左右旋转-30度</option>\r\n");
      out.write("\t\t\t<option>左右旋转-45度</option>\r\n");
      out.write("\t\t\t<option>左右旋转-60度</option>\r\n");
      out.write("\t\t\t<option>左右旋转-90度</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"上下旋转\">\r\n");
      out.write("\t\t\t<option>上下旋转30度</option>\r\n");
      out.write("\t\t\t<option>上下旋转45度</option>\r\n");
      out.write("\t\t\t<option>上下旋转60度</option>\r\n");
      out.write("\t\t\t<option>上下旋转90度</option>\r\n");
      out.write("\t\t\t<option>上下旋转-30度</option>\r\n");
      out.write("\t\t\t<option>上下旋转-45度</option>\r\n");
      out.write("\t\t\t<option>上下旋转-60度</option>\r\n");
      out.write("\t\t\t<option>上下旋转-90度</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr id=\"operation_table\"><td>组件操作:&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>选择操作<br/>\r\n");
      out.write("\t<select  id=\"component_selection_operation\" onchange=\"select_component_operation('component_selection_operation');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<optgroup label=\"清除组件选择\">\r\n");
      out.write("\t\t\t<option>清除选择</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t<optgroup label=\"执行组件选择\">\r\n");
      out.write("\t\t\t<option>上层组件</option>\r\n");
      out.write("\t\t\t<option>下层组件</option>\r\n");
      out.write("\t\t\t<option>移动组件</option>\r\n");
      out.write("\t\t\t<option>最近选中</option>\r\n");
      out.write("\t\t\t<option>所有组件</option>\r\n");
      out.write("\t\t\t<option>可见组件</option>\r\n");
      out.write("\t\t\t<option>显示组件</option>\r\n");
      out.write("\t\t\t<option>选择组件</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>剖分操作<br/>\r\n");
      out.write("\t<select  id=\"component_clip_operation\" onchange=\"process_component_operation('component_clip_operation');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>执行剖分</option>\r\n");
      out.write("\t\t<option>取消剖分</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>隐藏操作<br/>\r\n");
      out.write("\t<select  id=\"component_hide_operation\" onchange=\"hide_component_operation('component_hide_operation');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>隐藏组件</option>\r\n");
      out.write("\t\t<option>显示组件</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>列表操作<br/>\r\n");
      out.write("\t<select  id=\"component_list_operation\" onchange=\"process_component_operation('component_list_operation');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>组件类型列表</option>\r\n");
      out.write("\t\t<option>组件树列表</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr id=\"parameter_table\"><td>系统参数:&nbsp;&nbsp;&nbsp;&nbsp;<br/><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>信息查询<br/>\r\n");
      out.write("\t<select  id=\"system_information_id\" onchange=\"display_system_information('system_information_id');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"系统信息\">\r\n");
      out.write("\t\t<option>复位系统信息</option>\r\n");
      out.write("\t\t<option>提取系统信息</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"杆件信息\">\r\n");
      out.write("\t\t<option>顺序排列杆件</option>\r\n");
      out.write("\t\t<option>排序排列杆件</option>\r\n");
      out.write("\t\t<option>阵列排列杆件</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"组件信息\">\r\n");
      out.write("\t\t<option>组件树</option>\r\n");
      out.write("\t\t<option>选中组件</option>\r\n");
      out.write("\t\t<option>排序组件</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<optgroup label=\"收集器信息\">\r\n");
      out.write("\t\t<option>列表收集器</option>\r\n");
      out.write("\t\t<option>显示收集器</option>\r\n");
      out.write("\t\t<option>选择收集器</option>\r\n");
      out.write("\t\t<option>渲染目标收集器</option>\r\n");
      out.write("\t\t</optgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<option>相机信息</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<option>二维码</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</select><br/><br/>\r\n");
      out.write("\r\n");
      out.write("\t</td><td>配音设置<br/>\r\n");
      out.write("\t<select  id=\"set_sound_id\" onchange=\"process_set_sound('set_sound_id');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>打开配音</option>\r\n");
      out.write("\t\t<option>关闭配音</option>\r\n");
      out.write("\t</select><br/><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>\r\n");
      out.write("\t<output id=\"level_of_detail_output\"\tname=\"level_of_detail_output\">层次细节</output><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<select  id=\"level_of_detail\"\tonclick=\"switch_level_of_detail();\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>放弃和选择</option>\r\n");
      out.write("\t\t<option>仅仅执行放弃</option>\r\n");
      out.write("\t\t<option>关闭层次细节</option>\r\n");
      out.write("\t</select><br/>\r\n");
      out.write("\t<input type=\"range\"  id=\"level_of_detail_input\" min=\"0\" max=\"1000\"\tstyle=\"width:200px\" onchange=\"adjust_level_of_detail();\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>\r\n");
      out.write("\t\t<output id=\"display_precision_label\"\tname=\"display_precision_label\">显示精度</output><br/>\r\n");
      out.write("\t\t<input \ttype=\"range\" id=\"mouse_down_range\" min=\"1\" max=\"1000\" style=\"width:200px\"\tonchange=\"adjust_display_precision(true);\"><br/>\r\n");
      out.write("\t\t<input\ttype=\"range\"  id=\"mouse_up_range\" min=\"1\" max=\"1000\" style=\"width:200px\"\tonchange=\"adjust_display_precision(false);\">\r\n");
      out.write("\t\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<tr id=\"mount_table\"><td>拼装控制:&nbsp;&nbsp;&nbsp;&nbsp;<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>拼装控制<br/>\r\n");
      out.write("\t<select  id=\"component_movement_control\" onchange=\"process_component_operation('component_movement_control');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>向前拼装</option>\r\n");
      out.write("\t\t<option>向后拆卸</option>\r\n");
      out.write("\t\t<option>拼装暂停</option>\r\n");
      out.write("\t\t<option>拼装跳转</option>\r\n");
      out.write("\t</select><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>\r\n");
      out.write("\t<output id=\"mount_speed_label\"\tname=\"mount_speed_label\">拼装速度</output><br/>\r\n");
      out.write("\t<input type=\"range\"  \tid=\"mount_speed_range\" \t\t\tmin=\"0\" max=\"1000\"\tstyle=\"width:200px\"\r\n");
      out.write("\t \tonchange=\"adjust_mount_speed('mount_speed_range','mount_speed_label');\"><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>\r\n");
      out.write("\t<output id=\"mount_precision_label\"\tname=\"mount_precision_label\">拼装精度</output><br/>\r\n");
      out.write("\t<input type=\"range\"  \tid=\"mount_granularity_range\" \tmin=\"0\" max=\"1000\"\tstyle=\"width:200px\"\r\n");
      out.write("\t \tonchange=\"adjust_mount_granularity('mount_granularity_range','mount_precision_label');\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td><td>拼装设计<br/>\r\n");
      out.write("\t<select  id=\"component_movement_design\" onchange=\"process_component_operation('component_movement_design');\">\r\n");
      out.write("\t\t<option></option>\r\n");
      out.write("\t\t<option>拼装设计</option>\r\n");
      out.write("\t\t<option>拼装编辑</option>\r\n");
      out.write("\t\t<option>拼装查询</option>\r\n");
      out.write("\t</select><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\"  value=\"太阳升起\" \tid=\"sun_rise\" \t\t\tstyle=\"width:150px;height:30px\"\r\n");
      out.write("\t\tonclick=\"sun_rise();play_sound('sound/1.mp3');\"/>\r\n");
      out.write("<input type=\"button\"  value=\"太阳落山\" \tid=\"sun_set\" \t\t\tstyle=\"width:150px;height:30px\"\r\n");
      out.write("\t\tonclick=\"sun_set();play_sound('sound/2.mp3');\"/>\r\n");
      out.write("<input type=\"button\"  value=\"黄赤交角\" \tid=\"angle\" \t\t\t\tstyle=\"width:150px;height:30px\"\r\n");
      out.write("\t\tonclick=\"angle();eclipse(false);play_sound('sound/3.mp3');\"/>\t\t\r\n");
      out.write("<input type=\"button\"  value=\"极昼极夜\" \tid=\"polar_day_night\" \tstyle=\"width:150px;height:30px\"\r\n");
      out.write("\t\tonclick=\"polar_day_night();play_sound('sound/4.mp3');\"/>\r\n");
      out.write("<input type=\"button\"  value=\"日食月食\" \tid=\"eclipse\"\t \t\tstyle=\"width:150px;height:30px\"\r\n");
      out.write("\t\tonclick=\"camera_0_parameter();eclipse(true);restore_orientation_camera();play_sound('sound/5.mp3');\"/>\r\n");
      out.write("<input type=\"button\"  value=\"太阳系\" \t\tid=\"solar_system\" \tstyle=\"width:150px;height:30px\"\r\n");
      out.write("\t\tonclick=\"camera_0_parameter();eclipse(false);restore_orientation_camera();play_sound('sound/6.mp3');\"/>\r\n");
      out.write("<input type=\"button\"  value=\"全屏幕\" \t\tid=\"full_screen\" \tstyle=\"width:150px;height:30px\"\r\n");
      out.write("\t\tonclick=\"render_object.utility.set_clear_fullscreen(true);\"/>\r\n");
      out.write("\r\n");
      out.write(" <br/> <br/>\r\n");
      out.write(" <audio id=\"audio_player\"\tautoplay=\"autoplay\" controls=\"controls\"\tstyle=\"width:800px;height:40px\">\t</audio>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
