/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2021-03-01 07:48:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sinked_005fpipe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gps_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>orientation</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var version=0;\r\n");
      out.write("\r\n");
      out.write("function process_position(position)\r\n");
      out.write("{\r\n");
      out.write("\tvar latitude\t=position.coords.latitude;\r\n");
      out.write("\tvar longitude\t=position.coords.longitude;\r\n");
      out.write("\tvar altitude\t=position.coords.altitude;\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"version\").value\t=\"version:\"+version;\r\n");
      out.write("\tdocument.getElementById(\"longitude\").value\t=\"longitude:\"+longitude;\r\n");
      out.write("\tdocument.getElementById(\"latitude\").value\t=\"latitude: \"+latitude;\r\n");
      out.write("\t\r\n");
      out.write("\tif(typeof(altitude)==\"number\")\r\n");
      out.write("\t\tdocument.getElementById(\"altitude\").value\t=\"altitude: \"+altitude;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\taltitude=20;\r\n");
      out.write("\t\tdocument.getElementById(\"altitude\").value\t=\"altitude is wrong\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar url=\"sensor.jsp?operation=\";\r\n");
      out.write("\turl+=((version++)==0)?\"set_gps_origin\":\"set_origin_by_gps\";\r\n");
      out.write("\turl+=\"&sensor_data=\"+latitude+\",\"+longitude+\",\"+altitude;\r\n");
      out.write("\t\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\tvar my_ajax=new XMLHttpRequest();\r\n");
      out.write("\t\tmy_ajax.onreadystatechange=function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttry{\r\n");
      out.write("\t\t\t\tif(my_ajax.readyState==4)\r\n");
      out.write("\t\t\t\t\tif(my_ajax.status==200)\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"result\").value=\"Result:\"+my_ajax.responseText.trim();\r\n");
      out.write("\t\t\t}catch(e){\r\n");
      out.write("\t\t\t\talert(\"error:\"+e.toString());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tmy_ajax.open(\"GET\",url,true);\r\n");
      out.write("\t\tmy_ajax.send(null);\r\n");
      out.write("\t}catch(e){\r\n");
      out.write("\t\t;\r\n");
      out.write("\t};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function init()\r\n");
      out.write("{\r\n");
      out.write("\tnavigator.geolocation.watchPosition(process_position);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"init();\">\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<h1>\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("<output id=\"longitude\"></output><br/>\r\n");
      out.write("<output id=\"latitude\"></output><br/>\r\n");
      out.write("<output id=\"altitude\"></output><br/><br/>\r\n");
      out.write("<output id=\"version\"></output><br/><br/>\r\n");
      out.write("<output id=\"result\"></output><br/><br/>\r\n");
      out.write("</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
