/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2021-03-26 03:36:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.chinese;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class draw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

{
	String str;
	out.println("var user_name=\""				+(((str=request.getParameter("user_name"				))==null)?"NoName":str)+"\";");
	out.println("var pass_word=\""				+(((str=request.getParameter("pass_word"				))==null)?"NoPassword":str)+"\";");	
	out.println("var scene_name=\""				+(((str=request.getParameter("scene_name"				))==null)?"test":str)+"\";");
	out.println("var link_name=\""				+(((str=request.getParameter("link_name"				))==null)?"":str)+"\";");
	out.println("var change_part=\""			+(((str=request.getParameter("change_part"				))==null)?"":str)+"\";");
	out.println("var change_component=\""		+(((str=request.getParameter("change_component"			))==null)?"":str)+"\";");
	out.println("var part_type=\""				+(((str=request.getParameter("part_type"				))==null)?"":str)+"\";");
	out.println("var sub_directory=\""			+(((str=request.getParameter("sub_directory"			))==null)?"":str)+"\";");
	out.println("var coordinate=\""				+(((str=request.getParameter("coordinate"				))==null)?"xyz":str)+"\";");
	out.println("var max_loading_number=\""		+(((str=request.getParameter("max_loading_number"		))==null)?"5":str)+"\";");
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../interface.jsp?function_name=construct_render_object\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var render,collector_stack_version=0;\r\n");
      out.write("\r\n");
      out.write("function body_onload()\r\n");
      out.write("{\r\n");
      out.write("//\tdocument.oncontextmenu=function(){return false;}\r\n");
      out.write("\r\n");
      out.write("\tconstruct_render_object(\r\n");
      out.write("\t\tdocument.getElementById(\"my_canvas\"),\r\n");
      out.write("\t\tuser_name,pass_word,\"chinese\",scene_name,link_name,\r\n");
      out.write("\t\t[\r\n");
      out.write("\t\t\t[\"change_part\",\t\t\t\tchange_part\t\t\t],\r\n");
      out.write("\t\t\t[\"change_component\",\t\tchange_component\t],\r\n");
      out.write("\t\t\t[\"part_type\",\t\t\t\tpart_type\t\t\t],\r\n");
      out.write("\t\t\t[\"sub_directory\",\t\t\tsub_directory\t\t],\r\n");
      out.write("\t\t\t[\"coordinate\",\t\t\t\tcoordinate\t\t\t],\r\n");
      out.write("\t\t\t[\"max_loading_number\",\t\tmax_loading_number\t]\r\n");
      out.write("\t\t],\r\n");
      out.write("\t\tfunction(my_render)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\trender=my_render;\r\n");
      out.write("\t\t\tdocument.title=render.title;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\trender.user_call_processor.turnoff_control_panel();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\trender.append_routine_function(\r\n");
      out.write("\t\t\t\t\tfunction(render)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tif(render.collector_stack_version!=collector_stack_version){\r\n");
      out.write("\t\t\t\t\t\t\tcollector_stack_version=render.collector_stack_version;\r\n");
      out.write("\t\t\t\t\t\t\trender.user_call_processor.reload_control_panel();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t},\"init in draw.jsp\"\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function body_onunload()\r\n");
      out.write("{\r\n");
      out.write("\tif(typeof(render)==\"object\")\r\n");
      out.write("\t\tif(render!=null)\r\n");
      out.write("\t\t\tif(typeof(render.terminate)==\"function\")\r\n");
      out.write("\t\t\t\trender.terminate();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function body_onresize()\r\n");
      out.write("{\r\n");
      out.write("\tif(typeof(render)==\"object\")\r\n");
      out.write("\t\tif(render!=null)\r\n");
      out.write("\t\t\tif(typeof(render.user_call_processor)==\"object\")\r\n");
      out.write("\t\t\t\tif(render.user_call_processor!=null)\r\n");
      out.write("\t\t\t\t\tif(typeof(render.user_call_processor.resize)==\"function\")\r\n");
      out.write("\t\t\t\t\t\trender.user_call_processor.resize();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"body_onload();\" onunload=\"body_onunload();\" onresize=\"body_onresize();\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align:left\"\talign=\"center\"\t\t\t\t\t\t>\r\n");
      out.write("\t<canvas id=\"my_canvas\"\t\ttabindex=\"0\"\t\t\t\t\t\t></canvas>\r\n");
      out.write("\t<iframe id=\"my_part_list\"\ttabindex=\"1\"\thidden=\"hidden\"\t\t></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
