/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2020-11-25 08:48:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class locate_005fsinked_005fpipe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<title>设计</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");

String str;
str=request.getParameter("url");
out.print("var url=decodeURIComponent(\""+str+"\")");
str=request.getParameter("channel");
out.print(",channel=\""+str+"&user_name=NoName\"");


      out.write("\r\n");
      out.write("\r\n");
      out.write("var sinked_pipe_id=0;\r\n");
      out.write("\r\n");
      out.write("function set_location()\r\n");
      out.write("{\r\n");
      out.write("\tvar str;\r\n");
      out.write("\tstr =url+\"?channel=\"+channel+\"&command=component&method=event\";\r\n");
      out.write("\tstr+=\"&event_component_name=movement_manager\";\r\n");
      out.write("\tstr+=\"&operation=design&move_method=design\";\r\n");
      out.write("\tstr+=\"&design_operation=set_location&coordinate=component\";\r\n");
      out.write("\t\r\n");
      out.write("\tstr+=\"&component_name=\"+encodeURIComponent(encodeURIComponent(\"管段最终对接_\"+sinked_pipe_id.toString()));\r\n");
      out.write("\t\r\n");
      out.write("\tstr+=\"&mx=\"+((document.getElementById(\"mx\").value*1000).toString());\r\n");
      out.write("\tstr+=\"&my=\"+((document.getElementById(\"my\").value*1000).toString());\r\n");
      out.write("\tstr+=\"&mz=\"+((document.getElementById(\"mz\").value*1000).toString());\r\n");
      out.write("\t\r\n");
      out.write("\tstr+=\"&rx=\"+(document.getElementById(\"rx\").value.toString());\r\n");
      out.write("\tstr+=\"&ry=\"+(document.getElementById(\"ry\").value.toString());\r\n");
      out.write("\tstr+=\"&rz=\"+(document.getElementById(\"rz\").value.toString());\r\n");
      out.write("\t\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\tvar lfy_ajax=new XMLHttpRequest();\r\n");
      out.write("\t\tlfy_ajax.onreadystatechange=function(){\t\t\r\n");
      out.write("\t\t\tif(lfy_ajax.readyState==4)\r\n");
      out.write("\t\t\t\t;\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tlfy_ajax.open(\"GET\",str,true);\r\n");
      out.write("\t\tlfy_ajax.send(null);\r\n");
      out.write("\t}catch(e){\r\n");
      out.write("\t\t;\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("function get_location(move_flag,rotate_flag)\r\n");
      out.write("{\r\n");
      out.write("\tvar str=url+\"?channel=\"+channel;\r\n");
      out.write("\t\r\n");
      out.write("\tstr+=\"&command=component&method=event&event_component_name=movement_manager\";\r\n");
      out.write("\tstr+=\"&operation=design&move_method=design&design_operation=get_location\";\r\n");
      out.write("\t\r\n");
      out.write("\tstr+=\"&component_name=\"+encodeURIComponent(encodeURIComponent(\"管段最终对接_\"+sinked_pipe_id.toString()));\r\n");
      out.write("\t\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\tvar lfy_ajax=new XMLHttpRequest();\r\n");
      out.write("\t\tlfy_ajax.onreadystatechange=function(){\t\t\r\n");
      out.write("\t\t\tif(lfy_ajax.readyState!=4)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tif(lfy_ajax.status!=200)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tvar p=JSON.parse(lfy_ajax.responseText);\r\n");
      out.write("\t\t\tif(move_flag){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"mx\").value=p.mx/1000;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"my\").value=p.my/1000;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"mz\").value=p.mz/1000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(rotate_flag){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rx\").value=p.rx;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"ry\").value=p.ry;\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rz\").value=p.rz;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tlfy_ajax.open(\"GET\",str,true);\r\n");
      out.write("\t\tlfy_ajax.send(null);\r\n");
      out.write("\t}catch(e){\r\n");
      out.write("\t\t;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function reset_move()\r\n");
      out.write("{\t\r\n");
      out.write("\tdocument.getElementById(\"mx\").value=0;\r\n");
      out.write("\tdocument.getElementById(\"my\").value=0;\r\n");
      out.write("\tdocument.getElementById(\"mz\").value=0;\r\n");
      out.write("\tset_location();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function reset_rotate()\r\n");
      out.write("{\t\r\n");
      out.write("\tdocument.getElementById(\"rx\").value=0;\r\n");
      out.write("\tdocument.getElementById(\"ry\").value=0;\r\n");
      out.write("\tdocument.getElementById(\"rz\").value=0;\r\n");
      out.write("\tset_location();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function set_sinked_pipe(id)\r\n");
      out.write("{\r\n");
      out.write("\tsinked_pipe_id=id;\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<4;i++)\r\n");
      out.write("\t\tdocument.getElementById(\"sinked_pipe_radio_\"+i.toString()).checked=false;\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"sinked_pipe_radio_\"+sinked_pipe_id.toString()).checked=true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_sinked_pipe()\r\n");
      out.write("{\r\n");
      out.write("\tvar my_url_head=url+\"?channel=\"+channel;\r\n");
      out.write("\t\r\n");
      out.write("\tmy_url_head+=\"&command=component&method=event\";\r\n");
      out.write("\tmy_url_head+=\"&event_component_name=manipulator_component\";\r\n");
      out.write("\tmy_url_head+=\"&event_method=show_hide_component\";\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<4;i++){\r\n");
      out.write("\t\tvar my_url=my_url_head;\r\n");
      out.write("\t\tif(document.getElementById(\"sinked_pipe_check_\"+i.toString()).checked)\r\n");
      out.write("\t\t\tmy_url+=\"&event_operation=show&component_name=\";\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tmy_url+=\"&event_operation=hide&component_name=\";\r\n");
      out.write("\t\tmy_url+=encodeURIComponent(encodeURIComponent(\"管段最终对接_\"+i.toString()));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttry{\r\n");
      out.write("\t\t\tvar lfy_ajax=new XMLHttpRequest();\r\n");
      out.write("\t\t\tlfy_ajax.open(\"GET\",my_url,true);\r\n");
      out.write("\t\t\tlfy_ajax.send(null);\r\n");
      out.write("\t\t}catch(e){\r\n");
      out.write("\t\t\t;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"get_location(true,true);check_sinked_pipe();\">\r\n");
      out.write("\r\n");
      out.write("<form style=\"white-space:nowrap;text-align:center;vertical-align:top\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr/><h3>沉管平移</h3>\r\n");
      out.write("X:<input type=\"number\" \tname=\"mx\"\t\t\tid=\"mx\"\t\t\t\t\t\t\tonkeyup=\"set_location();\"\tonclick=\"set_location();\"\tstyle=\"width:100px;\">\r\n");
      out.write("Y:<input type=\"number\"\tname=\"my\"\t\t\tid=\"my\"\t\t\t\t\t\t\tonkeyup=\"set_location();\"\tonclick=\"set_location();\"\tstyle=\"width:100px;\">\r\n");
      out.write("Z:<input type=\"number\"\tname=\"mz\"\t\t\tid=\"mz\"\t\t\t\t\t\t\tonkeyup=\"set_location();\"\tonclick=\"set_location();\"\tstyle=\"width:100px;\"><br/>\r\n");
      out.write("<input type=\"button\"\tname=\"m_get\"\t\tid=\"m_get\"\t\tvalue=\"提取\"\t\t\t\t\t\t\t\t\tonclick=\"get_location(true,false);\"\t\t\t\t>\r\n");
      out.write("<input type=\"button\"\tname=\"m\"\t\t\tid=\"m\"\t\t\tvalue=\"复位\"\t\t\t\t\t\t\t\t\tonclick=\"reset_move();\"\t\t\t\t\t\t\t><br/>\r\n");
      out.write("\r\n");
      out.write("<hr/><h3>沉管旋转</h3>\r\n");
      out.write("X:<input type=\"number\"\tname=\"rx\"\t\t\tid=\"rx\"\t\t\t\t\t\t\tonkeyup=\"set_location();\"\tonclick=\"set_location();\"\tstyle=\"width:100px;\">\r\n");
      out.write("Y:<input type=\"number\"\tname=\"ry\"\t\t\tid=\"ry\"\t\t\t\t\t\t\tonkeyup=\"set_location();\"\tonclick=\"set_location();\"\tstyle=\"width:100px;\">\r\n");
      out.write("Z:<input type=\"number\"\tname=\"rz\"\t\t\tid=\"rz\"\t\t\t\t\t\t\tonkeyup=\"set_location();\"\tonclick=\"set_location();\"\tstyle=\"width:100px;\"><br/>\r\n");
      out.write("<input type=\"button\"\tname=\"m_get\"\t\tid=\"r_get\"\t\tvalue=\"提取\"\t\t\t\t\t\t\t\t\tonclick=\"get_location(false,true);\"\t\t\t\t>\r\n");
      out.write("<input type=\"button\"\tname=\"r\"\t\t\tid=\"r\"\t\t\tvalue=\"复位\"\t\t\t\t\t\t\t\t\tonclick=\"reset_rotate();\"\t\t\t\t\t\t><br/>\r\n");
      out.write("\r\n");
      out.write("<hr/><h3>沉管选择</h3>\r\n");
      out.write("<input id=\"sinked_pipe_check_0\"\t\ttype=\"checkbox\"\tonclick=\"check_sinked_pipe();\">\r\n");
      out.write("<input id=\"sinked_pipe_radio_0\"\t\ttype=\"radio\"\tonclick=\"set_sinked_pipe  (0);\">第一沉管\r\n");
      out.write("\r\n");
      out.write("<input id=\"sinked_pipe_check_1\"\t\ttype=\"checkbox\"\tonclick=\"check_sinked_pipe();\">\r\n");
      out.write("<input id=\"sinked_pipe_radio_1\"\t\ttype=\"radio\"\tonclick=\"set_sinked_pipe  (1);\">第二沉管\r\n");
      out.write("\r\n");
      out.write("<input id=\"sinked_pipe_check_2\"\t\ttype=\"checkbox\"\tonclick=\"check_sinked_pipe();\">\r\n");
      out.write("<input id=\"sinked_pipe_radio_2\"\t\ttype=\"radio\"\tonclick=\"set_sinked_pipe  (2);\">第三沉管\r\n");
      out.write("\r\n");
      out.write("<input id=\"sinked_pipe_check_3\"\t\ttype=\"checkbox\"\tonclick=\"check_sinked_pipe();\">\r\n");
      out.write("<input id=\"sinked_pipe_radio_3\"\t\ttype=\"radio\"\tonclick=\"set_sinked_pipe  (3);\">第四沉管\r\n");
      out.write("\r\n");
      out.write("<hr/>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
